eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://euraka-server-alb-38289861.cn-northwest-1.elb.amazonaws.com.cn:8889/eureka/
server:
  #当前服务端口号
  port: 8762
spring:
  application:
    #当前应用名称
    name: service-hi